# Generated by Django 5.1 on 2024-08-27 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('category', models.CharField(choices=[('clothes', 'Clothes'), ('JEWELLERY', 'Jewellery')], max_length=100)),
                ('price', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('addAt', models.DateTimeField(auto_now_add=True)),
                ('brandName', models.CharField(max_length=100)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
